language: python
python:
- '3.6'
- '3.7'
- '3.8'
- '3.9'
install: pip install -r requirements.txt
script: nosetests
deploy:
  provider: pypi
  username: __token__
  password:
    secure: IjXBHwrD1P8AxZ1KXIEPpLN4FRhsHq6oJygc9ooj8JqHsc8LLm8oq8RclH+y63OWCvT1ayrmWHesE5F5Q297rws9JdXLcJ+2LN97PTO0fPfPzdm4BwF2EGQMaN3okOm7Rij6IqvUcm4fv9pNauK8BbpPF6PyB7Q3v5cjw3NfraCtsKSrYtfo2V9oNH08KRFzEff/1/6sa16q+V/RHxFqRipmsHuPShK9SXVj2R5utX/5RaDGuuawrWqYBa1dphuJ/h0cWn+DtWq4nBA/A9wy54G/AiNUsVuNnbF2urJ/3/AWaohVC4MiyRkZ99qRLv72k/J7ZEDnGGKQQzUIXolIurdztPfoWxSC2At2kBQyo5N13paXh+TEYc4pciRlYKBJ2I/x6syAElAXG/o+tbaY7oIr/qUOUshhXwdOq/8d+qngl1EvuiNYXj3GvsqzoF9AUGMIEZbfEObjbCZ3/BuWMWSClSSNEnMLp2FV/pg2Y391S6mqI7O83XaLiGqqifJ4LMCy7OmOsa4nao398mwqIjvMjsn5Oid0HWcVDeNc9L6MlW2pazg2RuecCg23k0YBU3iJ9vO1rFS9Ct/Bary7AiYjBMq40Y51brKxHj8BIdAnjnttxGZ9JNloF3iKllNWtUXcnPWYvPEHxb2GnkLHZlcFfjAb1T2GTGDFqRYIHQU=
  on:
    branch: main
