language: python
python:
- '3.6'
- '3.7'
- '3.8'
- '3.9'
install: pip install -r requirements.txt
script: nosetests
deploy:
  provider: pypi
  username: __token__
  on:
    branch: main
before_deploy:
  # set different name for pypi upload
  - sed -i -e 's/NAME = "leetcode"/NAME = "pyleetcode-api"/g' setup.py
